name: Deploy Hexo to HTML Branch

on:
  push:
    branches:
      - main  # 触发构建的分支，根据你的主分支名称修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2  # 检出代码

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # 使用 Node.js 14，根据你的项目需求修改

    - name: Install Dependencies
      run: npm install  # 安装 Hexo 项目依赖

    - name: Build Hexo
      run: npm run build  # 构建 Hexo 项目，确保你的 package.json 中有 "build" 脚本

    - name: Deploy to HTML Branch
      run: |
        git config --global user.email "1216692740@qq.com"
        git config --global user.name "BlockHaity"
        git checkout --orphan html
        git rm -rf .
        cp -r ./public/* ./
        git add .
        git commit -m "Update HTML branch"
        git push origin html --force
